name: PR Compliance Checklist

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  comment-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read checklist content
        id: checklist
        run: |
          content=$(cat docs/adr/compliance-checklist.md)
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "### ADR-000 Compliance Checklist\n---\n" >> $GITHUB_OUTPUT
          echo "Please review the changes against the following checklist based on our architectural decisions. Mark completed items.\n\n$content" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const body = `${process.env.checklist_body}`;
            await github.rest.issues.createComment({ owner, repo, issue_number, body });
            core.info(`Posted compliance checklist to PR #${issue_number}.`);

